apiVersion: apps/v1
kind: Deployment
metadata:
  name:  go-server
  labels:
    app:  go-server
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - image: go:1
        name:  go-server
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 2112
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 2112
          initialDelaySeconds: 30
          timeoutSeconds: 10    
        ports:
        - containerPort:  2112
          name:  metrics
        imagePullPolicy: Never